---
# handlers file for zabbix-agent

- name: restart zabbix-agent
  service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
    enabled: yes
  become: yes

- name: reload firewalld
  systemd:
    name: "{{ firewalld_service }}"
    state: reloaded
  become: yes
